### ISSUE TITLE
unknow flag error

### ISSUE THREAD

**Issue by lescuer97** [jp7677/dxvk-docker#5]
I'm trying to run the ./setup-dxvk-docker.sh but I'm getting this error when trying it to run it.
```
base-devel: Pulling from library/archlinux
Digest: sha256:ce6fcd78c698176b06f81cf2d1f881ca86f5fbc6b6078894af42a1fe1ea170df
Status: Image is up to date for archlinux:base-devel
docker.io/library/archlinux:base-devel
Sending build context to Docker daemon  89.57MB
Error response from daemon: dockerfile parse error line 9: Unknown flag: chown

```
I'm on docker version Docker version 20.10.12

the command runs correctly in this version of the code: https://github.com/jp7677/dxvk-docker/tree/021227e45b78483f7b4548011eddeea8d3e1f238

**Comment by jp7677** [comment]
Interesting. I'm running `podman` instead of docker but I assumed that both have nearly the same features/syntax. I guess I hit a difference here. 
~Does the setup completes for you when you remove `--chown=pkg:pkg` from line 9 in the `Dockerfile`~

**Comment by jp7677** [comment]
This should now be fixed on `master`, could you please retry?

**Comment by jp7677** [comment]
I'm assuming this has been fixed for your docker engine. Feel free to reopen when there are still issues.

**Comment by lescuer97** [comment]
I'm very sorry, did not see this.

yes it works correctly again
